# The name of the workflow
name: first-test

# The event that triggers the workflow
on: [push]

jobs:
  analysis:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
          architecture: x64
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        run: dart analyze .
#  widget-tests:
#    name: widget-tests
#    runs-on: ubuntu-latest
#    steps:
    # steps


# Output for this :
# Invalid workflow file: .github/workflows/first-test.yaml#L1
# No steps defined in `steps` and no workflow called in `uses` for the following jobs: analysis, widget-tests