# The name of the workflow
name: first-test

# The event that triggers the workflow
on: [push]

jobs:
  analysis:
    # The name of the job
    name: example
    runs-on: ubuntu-latest
    steps:
      - name: Echo Folder Contents
        run: echo $(ls)
#      - uses: actions/checkout@v3
#      - name: Initialize Flutter
#          uses: ./.github/actions/initialize-flutter
#      - name: Check Code Format
#        run: dart format . --set-exit-if-changed
#      - name: Analyze code
#        run: dart analyze .
#  widget-tests:
#    name: widget-tests
#    runs-on: ubuntu-latest
#    needs: analysis
#    steps:
#      - uses: actions/checkout@v3
#      - name: Initialize Flutter
#        uses: ./.github/actions/initialize-flutter
#      - name: Run tests
#        run: flutter test