# The name of the workflow
name: first-test

# The event that triggers the workflow
on: [push]

jobs:
  analysis:
    # The name of the job
    name: analysis
    runs-on: ubuntu-latest
    steps:
    # steps
    # The name of the job
  widget-tests:
    name: widget-tests
    runs-on: ubuntu-latest
    steps:
    # steps


# Output for this :
# Invalid workflow file: .github/workflows/first-test.yaml#L1
# No steps defined in `steps` and no workflow called in `uses` for the following jobs: analysis, widget-tests