# The name of the workflow
name: push-check

# The event that triggers the workflow
on: [push]

jobs:

  analysis:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/actions/initialize-flutter
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Analyze code
        run: dart analyze .

  widget-tests:
    name: widget-tests
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/actions/initialize-flutter
      - name: Run tests
        run: flutter test

  drive_android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ playstore ]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/actions/initialize-flutter

      # Run integration test
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/app_test.dart
